### ISSUE TITLE
pretrained_graph_encoder not include Prompt_generator weight

### ISSUE THREAD

**Issue by danielkaifeng** [HICAI-ZJU/KANO#6]
dear author, it is a great work of your implementation!
I have a questions concerning about saving pretrain encoder layer weights. 
Prompt_generator weights were not saved in encoder weights.  What is the insight of this?
Is it possible that down stream tasks preformance can be further improve by including  Prompt_generator weights, with attention_layer etc...

**Comment by ZJU-Fangyin** [comment]
Thank you for your interest in our work. 

The reason ``Prompt_generator`` weights are not included in the encoder weights during pre-training is because custom prompts are not typically used in this stage. Instead, prompts are used to elicit the potential of the pre-trained model, and are generally applied during the fine-tuning phase.

In our work, the prompt generator is also utilized during the fine-tuning stage, hence there is no need to save its weights during the pre-training phase.

I hope this addresses your question. Please feel free to contact us if you have any further queries!

**Comment by danielkaifeng** [comment]
Thanks, it is very clear for me now.
